# Generated by Django 5.0 on 2023-12-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('plant_season', models.CharField(max_length=255)),
                ('grow_time', models.IntegerField(max_length=255)),
                ('average_yield', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
