# Generated by Django 5.0 on 2023-12-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='grow_time',
            field=models.IntegerField(null=True),
        ),
    ]
