# Generated by Django 5.0 on 2023-12-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops_app', '0003_remove_crops_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='image',
            field=models.TextField(default='THis is an image', max_length=255),
        ),
    ]
