# Generated by Django 5.0 on 2023-12-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops_app', '0004_crops_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crops',
            old_name='image',
            new_name='picture',
        ),
    ]
