# Generated by Django 5.0 on 2023-12-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops_app', '0005_rename_image_crops_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='picture',
            field=models.TextField(max_length=255),
        ),
    ]
