# Generated by Django 5.0 on 2023-12-09 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals_app', '0001_initial'),
        ('crops_app', '0002_alter_crops_grow_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('animals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animals_app.animals')),
                ('crops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='crops_app.crops')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
