# Generated by Django 5.0 on 2023-12-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0001_initial'),
        ('crops_app', '0002_alter_crops_grow_time'),
        ('farm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='animals',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='crops',
        ),
        migrations.AddField(
            model_name='farm',
            name='animals',
            field=models.ManyToManyField(related_name='animals', to='animals_app.animals'),
        ),
        migrations.AddField(
            model_name='farm',
            name='crops',
            field=models.ManyToManyField(related_name='crops', to='crops_app.crops'),
        ),
    ]
